// Local content layer. All product/collection/page data is pre-parsed at build time
// from `raw messy data/` by `scripts/parse.mjs` into JSON files in `src/data/`.
import productsJson from "@/data/products.json"
import collectionsJson from "@/data/collections.json"
import pagesJson from "@/data/pages.json"
import postsJson from "@/data/posts.json"

let mediaManifest: Record<string, string> = {}
try {
  // Optional — generated by `scripts/download-images.mjs`. Falls back to remote CDN when missing.
  mediaManifest = require("@/data/media-manifest.json")
} catch {
  mediaManifest = {}
}

export type Price = { from: boolean; amount: number } | null

export type Product = {
  slug: string
  title: string
  url: string
  price: Price
  soldOut: boolean
  images: string[]
  sizes: string[]
  colors: string[]
  description: string
}

export type Collection = {
  slug: string
  title: string
  productSlugs: string[]
  image: string | null
}

export type Page = { slug: string; title: string; body: string }
export type Post = { slug: string; title: string; body: string; cover: string | null }

export const products = productsJson as Product[]
export const collections = collectionsJson as Collection[]
export const pages = pagesJson as Page[]
export const posts = postsJson as Post[]

const productBySlug = new Map(products.map((p) => [p.slug, p]))

export function getProduct(slug: string) {
  return productBySlug.get(slug)
}
export function getCollection(slug: string) {
  return collections.find((c) => c.slug === slug)
}
export function getPage(slug: string) {
  return pages.find((p) => p.slug === slug)
}
export function getPost(slug: string) {
  return posts.find((p) => p.slug === slug)
}

export function productsIn(collectionSlug: string) {
  const c = getCollection(collectionSlug)
  if (!c) return []
  return c.productSlugs.map((s) => productBySlug.get(s)).filter(Boolean) as Product[]
}

/** Resolves a Shopify CDN URL to a local /media path if it's been downloaded. */
export function mediaSrc(url: string | null | undefined): string {
  if (!url) return ""
  return mediaManifest[url] || url
}

export function formatPrice(p: Price): string {
  if (!p) return ""
  const value = `$${p.amount.toFixed(p.amount % 1 === 0 ? 0 : 2)}`
  return p.from ? `From ${value}` : value
}

// Editorial curation: surface specific collections in the navigation.
export const navTree = [
  {
    label: "Shop",
    href: "/shop",
    columns: [
      {
        title: "Be Caribbeing",
        items: [
          { label: "Varsity Sweatshirts", href: "/collections/varsity" },
          { label: "Caribpolitan Tings", href: "/collections/caribpolitan" },
          { label: "Hats + Accessories", href: "/collections/hats-accessories" },
          { label: "Bags + Totes", href: "/collections/bags-totes" },
        ],
      },
      {
        title: "For The Culture",
        items: [
          { label: "Jewelry Tings", href: "/collections/jewelry" },
          { label: "Art + Decor", href: "/collections/art-decor" },
          { label: "Book Tings", href: "/collections/books" },
          { label: "Aprons + Tea Towels", href: "/collections/aprons-tea-towels" },
          { label: "Vintage Finds", href: "/collections/marvalous-finds" },
        ],
      },
      {
        title: "Well-Being",
        items: [
          { label: "Body Tings", href: "/collections/body" },
          { label: "Candles + Incense", href: "/collections/candles-incense" },
        ],
      },
      {
        title: "Food + Beverage",
        items: [
          { label: "Food Tings", href: "/collections/food-tings" },
          { label: "Coffee + Tea + Mugs", href: "/collections/coffee-tea-mugs" },
        ],
      },
    ],
  },
  {
    label: "Gifts",
    href: "/shop?filter=gifts",
    columns: [
      {
        title: "By Price",
        items: [
          { label: "Under $50", href: "/collections/under-50" },
          { label: "Under $100", href: "/collections/under-101" },
        ],
      },
      {
        title: "By Recipient",
        items: [
          { label: "For Yuh Tantie Dem", href: "/collections/for-yuh-tantie-dem" },
          { label: "For Yuh Fren Dem", href: "/collections/for-yuh-fren-dem" },
          { label: "For Her", href: "/collections/for-her" },
          { label: "For Him", href: "/collections/for-him" },
          { label: "For Kids", href: "/collections/for-kids" },
        ],
      },
    ],
  },
  { label: "Journal", href: "/journal" },
  { label: "Visit", href: "/visit" },
  { label: "About", href: "/about" },
]
